// ANVI Recruitment OS — mock data
// Outstaffing recruitment platform. All exported to window for cross-script use.

const CLIENTS = [
  { id: "andy", name: "Andy Kessler", company: "Northwind SaaS", initials: "AK", country: "United States", tz: "PST", logo: "NW" },
  { id: "lena", name: "Lena Brandt", company: "Vektor Labs", initials: "LB", country: "Germany", tz: "CET", logo: "VL" },
  { id: "marco", name: "Marco Reyes", company: "Fintora", initials: "MR", country: "Spain", tz: "CET", logo: "FT" },
];

const VACANCIES = [
  {
    id: "v-fullstack",
    title: "Senior Full-Stack Developer",
    clientId: "andy",
    seniority: "Senior",
    type: "Outstaff · Full-time",
    location: "Remote · EU / LATAM",
    budgetMin: 28, budgetMax: 42, // client rate $/hr
    status: "Active Search",
    priority: "High",
    stack: ["React", "Next.js", "Node.js", "Express", "PostgreSQL", "SaaS"],
    niceToHave: ["AI tools", "Claude Code", "Cursor"],
    english: "B2+",
    created: "2 days ago",
    telegram: "@anvi_open · #fullstack",
    counts: { sourced: 12, screening: 5, sent: 2, approved: 1 },
    process: ["Initial filtering", "Screening questions", "Client review", "Client interview"],
    description: "Product-minded full-stack engineer to own features end-to-end on a fast-moving B2B SaaS. Strong React/Next.js on the front, Node/Express + Postgres on the back. Daily AI-assisted workflow is a big plus.",
  },
  {
    id: "v-ml",
    title: "ML Engineer (LLM / RAG)",
    clientId: "lena",
    seniority: "Senior",
    type: "Outstaff · Full-time",
    location: "Remote · EU",
    budgetMin: 45, budgetMax: 65,
    status: "Open",
    priority: "Urgent",
    stack: ["Python", "PyTorch", "RAG", "LangChain", "pgvector", "FastAPI"],
    niceToHave: ["LLM fine-tuning", "Vector DBs", "Evals"],
    english: "C1",
    created: "5 days ago",
    telegram: "@anvi_open · #ml",
    counts: { sourced: 8, screening: 3, sent: 0, approved: 0 },
    process: ["Initial filtering", "Tech screening", "Client review", "System design", "Offer"],
    description: "Build retrieval-augmented features and eval pipelines for a production LLM product. Comfortable across data, model, and serving layers.",
  },
  {
    id: "v-design",
    title: "Product Designer (B2B)",
    clientId: "marco",
    seniority: "Middle+",
    type: "Outstaff · Part-time",
    location: "Remote · EU",
    budgetMin: 30, budgetMax: 45,
    status: "Waiting for Client",
    priority: "Medium",
    stack: ["Figma", "Design Systems", "Prototyping", "B2B", "UX Research"],
    niceToHave: ["Fintech", "Webflow", "Motion"],
    english: "B2+",
    created: "1 week ago",
    telegram: "@anvi_open · #design",
    counts: { sourced: 6, screening: 4, sent: 3, approved: 1 },
    process: ["Portfolio review", "Screening", "Client review", "Design challenge"],
    description: "Own the design language for a fintech dashboard. Systems thinker who can move from research to polished UI quickly.",
  },
];

// Candidate database. costRate = internal $/hr, clientRate = shown to client.
const CANDIDATES = [
  {
    id: "c-artem", name: "Artem Valkov", title: "Senior Full-Stack Developer",
    country: "Ukraine", city: "Kyiv", tz: "EET", flag: "🇺🇦", initials: "AV",
    years: 7, seniority: "Senior", english: "B2 · Upper-Int", availability: "2 weeks",
    costRate: 24, clientRate: 34, salary: "$5,440 / mo",
    skills: ["React", "Next.js", "Node.js", "Express", "PostgreSQL", "SaaS", "TypeScript"],
    aiTools: ["Cursor", "Copilot"], source: "Telegram",
    match: { "v-fullstack": 86, "v-ml": 31, "v-design": 8 },
    tag: "Strongest technical fit",
    summary: "Senior full-stack engineer with 7+ years across React/Next.js front-ends and Node/Express back-ends on B2B SaaS. Daily Cursor + Copilot user. Recommended for first client interview.",
    fits: ["Direct React + Next.js depth", "SaaS product background", "Inside budget band", "Available in 2 weeks"],
    risks: ["No explicit Claude Code experience", "Verify system-design depth in interview"],
    status: "Sent to Client",
  },
  {
    id: "c-dmytro", name: "Dmytro Koval", title: "Full-Stack Engineer",
    country: "Poland", city: "Wrocław", tz: "CET", flag: "🇵🇱", initials: "DK",
    years: 5, seniority: "Middle+", english: "B2", availability: "Immediate",
    costRate: 20, clientRate: 29, salary: "$4,640 / mo",
    skills: ["React", "Node.js", "Express", "MongoDB", "Next.js", "REST"],
    aiTools: ["Copilot"], source: "Excel import",
    match: { "v-fullstack": 79, "v-ml": 22, "v-design": 10 },
    tag: "Best price / value",
    summary: "Pragmatic full-stack dev, 5 years, ships fast. Strong React + Node, lighter on Postgres. Best value in the current shortlist and available immediately.",
    fits: ["Available immediately", "Lowest rate in shortlist", "Solid React + Node core"],
    risks: ["Mongo-heavy, less Postgres", "English conversational, verify in call"],
    status: "Screening",
  },
  {
    id: "c-olek", name: "Oleksandr Hrytsenko", title: "Senior Software Engineer",
    country: "Ukraine", city: "Lviv", tz: "EET", flag: "🇺🇦", initials: "OH",
    years: 8, seniority: "Senior", english: "C1", availability: "1 month",
    costRate: 27, clientRate: 38, salary: "$6,080 / mo",
    skills: ["React", "Next.js", "Node.js", "GraphQL", "PostgreSQL", "AWS", "SaaS"],
    aiTools: ["Cursor", "Claude Code"], source: "LinkedIn",
    match: { "v-fullstack": 84, "v-ml": 40, "v-design": 6 },
    tag: "Best English",
    summary: "Senior engineer, 8 years, C1 English, daily Claude Code user. Strong across the stack with AWS and GraphQL. Great client-facing communicator.",
    fits: ["C1 English — client-facing ready", "Claude Code + Cursor daily", "AWS + GraphQL depth"],
    risks: ["Top of budget band", "1-month notice period"],
    status: "Sent to Client",
  },
  {
    id: "c-sofia", name: "Sofia Marin", title: "Frontend-leaning Full-Stack Dev",
    country: "Argentina", city: "Buenos Aires", tz: "ART", flag: "🇦🇷", initials: "SM",
    years: 6, seniority: "Senior", english: "B2+", availability: "3 weeks",
    costRate: 22, clientRate: 32, salary: "$5,120 / mo",
    skills: ["React", "Next.js", "TypeScript", "Tailwind", "Node.js", "SaaS"],
    aiTools: ["Cursor", "v0"], source: "Telegram",
    match: { "v-fullstack": 81, "v-ml": 18, "v-design": 44 },
    tag: "Fastest start",
    summary: "Frontend-leaning full-stack with strong product sense and Next.js depth. LATAM timezone overlaps US hours well. Comfortable with AI-native tooling.",
    fits: ["US-friendly timezone overlap", "Excellent Next.js + TS", "Product-minded"],
    risks: ["Back-end lighter than front", "Verify Postgres comfort"],
    status: "Screening",
  },
  {
    id: "c-pavel", name: "Pavel Novak", title: "Backend Engineer",
    country: "Czechia", city: "Brno", tz: "CET", flag: "🇨🇿", initials: "PN",
    years: 9, seniority: "Senior", english: "B2", availability: "1 month",
    costRate: 26, clientRate: 36, salary: "$5,760 / mo",
    skills: ["Node.js", "Express", "PostgreSQL", "Redis", "Docker", "Microservices"],
    aiTools: ["Copilot"], source: "Excel import",
    match: { "v-fullstack": 72, "v-ml": 35, "v-design": 4 },
    tag: null,
    summary: "Backend specialist, 9 years, infra-strong. Excellent for back-heavy work but lighter on modern front-end.",
    fits: ["Deep Node + Postgres", "Infra & microservices"],
    risks: ["Minimal React exposure", "Not a full-stack fit for this role"],
    status: "Sourced",
  },
  {
    id: "c-mira", name: "Mira Antonova", title: "ML Engineer",
    country: "Estonia", city: "Tallinn", tz: "EET", flag: "🇪🇪", initials: "MA",
    years: 6, seniority: "Senior", english: "C1", availability: "2 weeks",
    costRate: 38, clientRate: 54, salary: "$8,640 / mo",
    skills: ["Python", "PyTorch", "RAG", "LangChain", "pgvector", "FastAPI", "Evals"],
    aiTools: ["Claude Code", "Cursor"], source: "LinkedIn",
    match: { "v-fullstack": 28, "v-ml": 91, "v-design": 3 },
    tag: "Strongest technical fit",
    summary: "ML engineer with production RAG and eval pipeline experience. Built LLM features end-to-end. C1 English, available soon.",
    fits: ["Production RAG + evals", "pgvector + FastAPI serving", "C1 English"],
    risks: ["Top of budget band", "Confirm fine-tuning depth"],
    status: "Screening",
  },
  {
    id: "c-yuki", name: "Yuki Tanaka", title: "ML / Data Engineer",
    country: "Portugal", city: "Lisbon", tz: "WET", flag: "🇵🇹", initials: "YT",
    years: 5, seniority: "Middle+", english: "B2+", availability: "Immediate",
    costRate: 33, clientRate: 47, salary: "$7,520 / mo",
    skills: ["Python", "FastAPI", "RAG", "Vector DBs", "Airflow", "SQL"],
    aiTools: ["Cursor"], source: "Telegram",
    match: { "v-fullstack": 24, "v-ml": 83, "v-design": 2 },
    tag: "Fastest start",
    summary: "Data-leaning ML engineer with RAG and pipeline experience. Available immediately, mid-band rate.",
    fits: ["Available immediately", "RAG + data pipelines", "Mid-band rate"],
    risks: ["Lighter on model training", "Verify eval rigor"],
    status: "Sourced",
  },
  {
    id: "c-elena", name: "Elena Costa", title: "Product Designer",
    country: "Romania", city: "Cluj", tz: "EET", flag: "🇷🇴", initials: "EC",
    years: 6, seniority: "Senior", english: "C1", availability: "2 weeks",
    costRate: 25, clientRate: 36, salary: "$5,760 / mo",
    skills: ["Figma", "Design Systems", "B2B", "Prototyping", "UX Research", "Fintech"],
    aiTools: ["v0", "Figma AI"], source: "LinkedIn",
    match: { "v-fullstack": 9, "v-ml": 4, "v-design": 89 },
    tag: "Strongest technical fit",
    summary: "Senior product designer with B2B fintech depth and strong systems thinking. Moves from research to polished UI fast.",
    fits: ["B2B fintech experience", "Design systems owner", "C1 English"],
    risks: ["Part-time availability to confirm"],
    status: "Sent to Client",
  },
];

const RECRUITER = { name: "Daria Levin", initials: "DL", role: "Senior Recruiter", company: "ANVI" };

window.ANVI = { CLIENTS, VACANCIES, CANDIDATES, RECRUITER };
